spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/conpub
    username: pubble
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # JPA에서 발생하는 쿼리문을 콘솔창에 출력해줌.
        show_sql: true
        # SQL문장이 한줄에 나오는 것이 아니라 예쁘게나옴.
        format_sql: true
        globally_quoted_identifiers: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  devtools:
    livereload:
      enabled: true

  mail:
    host: smtp.naver.com
    port: 465
    username: minwtest1
    password: minwtest1!@
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true


logging.level:
  #JPA에서 발생하는 쿼리문을 로그파일로 보여주는 옵션
  org.hibernate.SQL: debug

  #SQL문에서 바인딩되는 파라미터 값까지 보여주는 옵션
  org.hibernate.type: trace


server:
  port: 8585